# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
      - main
pr:
  - main

pool: 'contabo'

variables:
  buildConfiguration: 'Release'

steps:
  - task: DotNetCoreCLI@2
    displayName: Restoring
    inputs:
      command: 'restore'
      projects: 'semantic-release.sln'
      feedsToUse: 'select'

  - task: DotNetCoreCLI@2
    displayName: Build - Debug
    inputs:
      command: 'build'
      projects: 'semantic-release.sln'

  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: 'test'
      projects: 'semantic-release.sln'
      
  - script: |
      - npm install -g npm@6
      - pip install --user bump2version
      - npm install @semantic-release/changelog
      - npm install @semantic-release/exec
      - npm install @semantic-release/git
      - npm install @semantic-release/github

